import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, CalendarDays, Check, MapPin, Navigation, Phone, ShieldCheck } from "lucide-react";
import { FAQJsonLd, LocalServiceJsonLd } from "@/components/seo/json-ld";
import { AppointmentCTA } from "@/components/shared/appointment-cta";
import { FAQList } from "@/components/shared/faq-list";
import { MapCard } from "@/components/shared/map-card";
import { PageHero } from "@/components/shared/page-hero";
import { Button } from "@/components/ui/button";
import { getLocalPage, localPages } from "@/data/locations";
import { createMetadata } from "@/lib/metadata";
import { aiImageAlt, locationImage } from "@/lib/page-images";
import { siteConfig } from "@/lib/site";

export function generateStaticParams(){return localPages.map(page=>({slug:page.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=getLocalPage(slug);if(!page)return{};return createMetadata({title:page.title,description:page.description,path:`/locations/${page.slug}`,image:locationImage(),noIndex:true,keywords:page.keywords})}

export default async function LocalPageRoute({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=getLocalPage(slug);if(!page)notFound();const faqs=[{question:`How do I book a psychiatrist appointment from ${page.name}?`,answer:`Call ${siteConfig.displayPhones[0]} for voice calls, WhatsApp ${siteConfig.whatsappDisplay}, or submit the short appointment request. The clinic will confirm availability before you travel.`},{question:`Is teleconsultation available for patients in ${page.name}?`,answer:"Teleconsultation may suit selected situations and follow-ups, subject to clinical suitability and applicable standards. Call to confirm; some first assessments and urgent concerns need in-person care."},{question:"What should I bring?",answer:"Bring current medicines, available past prescriptions or reports, a brief timeline and your questions. Do not delay urgent care to collect paperwork."},{question:"Is this an emergency clinic?",answer:"No. The clinic is not a 24-hour emergency department. For immediate danger, call 112 or go to the nearest emergency department. Tele-MANAS is available on 14416."}];return <><LocalServiceJsonLd name={page.title} description={page.description} path={`/locations/${page.slug}`} area={page.name}/><FAQJsonLd faqs={faqs}/><PageHero badge={`Care access from ${page.name}`} image={locationImage()} imageAlt={aiImageAlt(`mental healthcare access from ${page.name}`)} title={page.title} description={page.intro} breadcrumbs={[{label:"Locations",href:"/locations"},{label:page.name}]} actions={<><Button asChild><Link prefetch={false} href="/appointment"><CalendarDays/>Request appointment</Link></Button><Button asChild variant="outline"><a href={siteConfig.googleMapsUrl} target="_blank" rel="noreferrer"><Navigation/>Live directions</a></Button></>} aside={<div className="rounded-[1.8rem] border border-border bg-card/85 p-6 shadow-soft"><MapPin className="size-6 text-secondary"/><h2 className="mt-4 text-lg font-extrabold">Plan before you travel</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{page.routeNote}</p><a href={`tel:${siteConfig.phones[0]}`} className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-primary"><Phone className="size-4"/>Confirm availability</a></div>}/>
<section className="container-page py-14 md:py-20"><div className="grid gap-8 lg:grid-cols-[1.05fr_.95fr]"><div><p className="eyebrow">Why patients contact the clinic</p><h2 className="section-title mt-5">Care for symptoms, function and family understanding.</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">People from {page.name} may seek assessment for low mood, anxiety, panic, OCD, sleep, addiction, attention, behaviour, psychosis, postpartum symptoms or memory change. You do not need to choose a diagnosis before booking.</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{["Consultant psychiatric assessment","Medication review when needed","Child, adult and older-adult care","De-addiction and relapse support","Family guidance with consent","In-person and selected tele-follow-up"].map(x=><li key={x} className="flex gap-3 text-sm leading-6 text-muted-foreground"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-secondary/12 text-secondary"><Check className="size-3" strokeWidth={3}/></span>{x}</li>)}</ul></div><div className="rounded-[1.8rem] bg-[#0b3b64] p-7 text-white"><ShieldCheck className="size-6 text-emerald-300"/><h2 className="mt-5 text-2xl font-extrabold tracking-[-0.035em]">Choosing the right psychiatrist</h2><p className="mt-4 text-sm leading-7 text-slate-200">Search phrases like “best” or “near me” are a starting point—not medical evidence. Consider qualifications, communication, ethical prescribing, privacy, fit, access and continuity. This page does not claim that one doctor is right for every person.</p><Link href="/psychiatrist-in-vijayawada" className="mt-5 inline-flex items-center gap-1 text-xs font-extrabold text-emerald-300">How to choose well<ArrowRight className="size-3.5"/></Link></div></div><div className="mt-10"><MapCard/></div><section className="mt-12 grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Local questions</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.04em]">Before travelling from {page.name}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Nearby reference areas include {page.nearby.join(", ")}. Use live routing rather than a fixed time estimate.</p></div><div className="rounded-[1.7rem] border border-border bg-card px-6 shadow-card"><FAQList faqs={faqs} schema={false}/></div></section></section><AppointmentCTA title={`Plan psychiatric care from ${page.name} with one direct call.`}/></>}
