import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Phone, ShieldAlert, UserRoundCheck, X } from "lucide-react";
import { PageHero } from "@/components/shared/page-hero";
import { Button } from "@/components/ui/button";
import { createMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = createMetadata({ title: "Mental Health Emergency Help in India", description: "Immediate mental-health crisis guidance: call 112 for danger, Tele-MANAS 14416 for free 24/7 support, and do not rely on routine appointment forms.", path: "/emergency", keywords: ["mental health emergency India", "suicide helpline India 14416", "Tele-MANAS", "emergency number 112"] });

export default function EmergencyPage() {
  return (<><PageHero badge="Immediate safety" title="If someone may not be safe, act now." description="This clinic website is not an emergency service and messages may not be read immediately. Use emergency or crisis services when danger is present." breadcrumbs={[{label:"Emergency guidance"}]} actions={<><Button asChild><a href="tel:112"><Phone/>Call 112 now</a></Button><Button asChild variant="outline"><a href="tel:14416">Call Tele-MANAS 14416</a></Button></>} />
  <section className="container-page py-14 md:py-20"><div className="grid gap-6 lg:grid-cols-2"><div className="rounded-[1.8rem] border border-amber-300/50 bg-amber-50 p-7 text-amber-950 dark:border-amber-400/25 dark:bg-amber-950/25 dark:text-amber-100"><ShieldAlert className="size-7"/><h2 className="mt-5 text-2xl font-extrabold tracking-[-0.035em]">Call 112 or go to an emergency department now if:</h2><ul className="mt-6 grid gap-4">{["There is a suicide attempt, current plan, intent or access to lethal means.","There is overdose, severe intoxication, seizure, collapse or breathing difficulty.","The person is violent, severely agitated or cannot be kept safe.","There is sudden confusion, fever with behaviour change, new weakness or head injury.","A postpartum parent is confused, not sleeping, hearing voices or holding unusual beliefs."].map(x=><li key={x} className="flex gap-3 text-sm leading-6"><X className="mt-0.5 size-5 shrink-0"/>{x}</li>)}</ul><Button asChild className="mt-7"><a href="tel:112"><Phone/>Call emergency services · 112</a></Button></div><div className="rounded-[1.8rem] border border-secondary/25 bg-secondary/7 p-7"><UserRoundCheck className="size-7 text-secondary"/><h2 className="mt-5 text-2xl font-extrabold tracking-[-0.035em]">While help is being arranged</h2><ul className="mt-6 grid gap-4">{["Stay with the person if you can do so safely.","Ask directly about suicide, a plan and access to means.","Reduce access to medicines, weapons, pesticides or other dangerous means if safe.","Speak calmly, use short sentences and avoid argument, shame or threats.","Do not promise secrecy about immediate danger.","Do not force transport alone if behaviour is unsafe; ask emergency services for guidance."].map(x=><li key={x} className="flex gap-3 text-sm leading-6 text-muted-foreground"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-secondary/12 text-secondary"><Check className="size-3" strokeWidth={3}/></span>{x}</li>)}</ul></div></div>
  <div className="mt-8 grid gap-5 md:grid-cols-3"><a href="tel:14416" className="rounded-2xl border border-border bg-card p-6 shadow-card"><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-secondary">Free · 24/7 · India</p><h2 className="mt-3 text-xl font-extrabold">Tele-MANAS · 14416</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">National tele-mental-health support in multiple languages.</p></a><a href={`tel:${siteConfig.emergency.teleManasLong}`} className="rounded-2xl border border-border bg-card p-6 shadow-card"><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-secondary">Alternative number</p><h2 className="mt-3 text-xl font-extrabold">1800-89-14416</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Tele-MANAS toll-free access.</p></a><div className="rounded-2xl border border-border bg-card p-6 shadow-card"><p className="text-xs font-extrabold uppercase tracking-[0.12em] text-primary">After immediate safety</p><h2 className="mt-3 text-xl font-extrabold">Plan follow-up</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Risk can change. Arrange continuing assessment after the crisis.</p><Link prefetch={false} href="/appointment" className="mt-4 inline-flex items-center gap-1 text-xs font-extrabold text-primary">Routine appointment<ArrowRight className="size-3.5"/></Link></div></div>
  <p className="mt-8 rounded-2xl border border-border bg-muted/55 p-5 text-xs leading-6 text-muted-foreground">Numbers verified against Government of India Tele-MANAS information. Service availability can change. In immediate danger, prioritise 112 and the nearest emergency department.</p></section></>);
}
