import { ArrowUpRight, Clock3, Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { BrandLogo } from "@/components/brand/logo";
import { BiText } from "@/components/i18n/bilingual-text";
import { conditions } from "@/data/conditions";
import { teConditions } from "@/data/te";
import { siteConfig, whatsappHref } from "@/lib/site";

const popular = ["depression", "anxiety", "ocd", "bipolar-disorder", "sleep-disorders", "alcohol-addiction"].map((slug) => conditions.find((item) => item.slug === slug)).filter(Boolean);
const care = [{en:"Services",te:"సేవలు",href:"/services"},{en:"Vijayawada clinic",te:"విజయవాడ క్లినిక్",href:"/clinic-vijayawada"},{en:"Doctor profile",te:"డాక్టర్ వివరాలు",href:"/doctor/pamarthi-krishna-das"},{en:"Treatments",te:"చికిత్స",href:"/treatments"},{en:"Patient journey",te:"రోగి ప్రయాణం",href:"/patient-journey"},{en:"Appointment",te:"అపాయింట్‌మెంట్",href:"/appointment"},{en:"Contact",te:"సంప్రదింపు",href:"/contact"},{en:"Gallery",te:"గ్యాలరీ",href:"/gallery"}];

export function SiteFooter() {
  return <footer className="border-t border-border bg-[#071a2b] text-slate-100"><div className="container-page py-14 md:py-18"><div className="grid gap-10 lg:grid-cols-[1.35fr_.8fr_.8fr_1.1fr]">
    <div><BrandLogo className="[&_span]:!text-white [&_span_span]:!text-slate-400"/><p className="mt-5 max-w-sm text-sm leading-7 text-slate-300"><BiText en="Compassionate, evidence-based psychiatric care focused on dignity, recovery, independence and quality of life." te="గౌరవం, కోలుకోవడం, స్వతంత్రత మరియు జీవన నాణ్యతపై దృష్టి పెట్టే దయతో కూడిన ఆధారిత మానసిక ఆరోగ్య సేవలు."/></p><p className="mt-4 text-sm font-extrabold text-white">Dr. Pamarthi Krishna Das</p><p className="mt-2 text-sm font-semibold text-emerald-300"><BiText en="Support for the mind. Hope for recovery." te="మనసుకు తోడు. కోలుకునే దారిలో ఆశ." /></p><div className="mt-6 flex flex-wrap gap-2"><a href="/privacy-policy" data-i18n-link className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300"><BiText en="Privacy" te="గోప్యత"/></a><a href="/terms" data-i18n-link className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300"><BiText en="Terms" te="నిబంధనలు"/></a><a href="/medical-disclaimer" data-i18n-link className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300"><BiText en="Medical disclaimer" te="వైద్య పరిమితులు"/></a><a href="/emergency" data-i18n-link className="rounded-full border border-amber-300/25 px-3 py-1.5 text-xs text-amber-200"><BiText en="Urgent help" te="అత్యవసర సహాయం"/></a><a href={siteConfig.googleMapsUrl} target="_blank" rel="noreferrer" className="rounded-full border border-white/10 px-3 py-1.5 text-xs text-slate-300"><BiText en="Directions" te="దిశలు"/></a></div></div>
    <div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400"><BiText en="Care" te="సంరక్షణ"/></p><ul className="mt-4 grid gap-3 text-sm">{care.map(item=><li key={item.href}><a href={item.href} data-i18n-link className="text-slate-300 hover:text-white"><BiText en={item.en} te={item.te}/></a></li>)}</ul></div>
    <div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400"><BiText en="Conditions" te="పరిస్థితులు"/></p><ul className="mt-4 grid gap-3 text-sm">{popular.map(item=>item&&<li key={item.slug}><a href={`/conditions/${item.slug}`} data-i18n-link className="text-slate-300 hover:text-white"><BiText en={item.name} te={teConditions[item.slug].name}/></a></li>)}<li><a href="/conditions" data-i18n-link className="inline-flex items-center gap-1 text-emerald-300"><BiText en="View all" te="అన్నీ చూడండి"/><ArrowUpRight className="size-3.5"/></a></li></ul></div>
    <div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-slate-400"><BiText en="Visit the clinic" te="క్లినిక్ చిరునామా"/></p><ul className="mt-4 grid gap-4 text-sm text-slate-300"><li className="flex gap-3"><MapPin className="mt-0.5 size-4.5 shrink-0 text-emerald-300"/><span>{siteConfig.address.line1}<br/>{siteConfig.address.line2}<br/>{siteConfig.address.locality}, {siteConfig.address.city} {siteConfig.address.postalCode}</span></li><li className="flex gap-3"><Clock3 className="mt-0.5 size-4.5 shrink-0 text-emerald-300"/><span><BiText en={siteConfig.hours.summary} te="సోమ–శని · ఉదయం 9–రాత్రి 9"/><br/><span className="text-slate-400"><BiText en="Sunday closed · Call to confirm" te="ఆదివారం సెలవు · ముందుగా కాల్ చేయండి"/></span></span></li><li><a href={`tel:${siteConfig.phones[0]}`} className="flex items-center gap-3"><Phone className="size-4.5 text-emerald-300"/>{siteConfig.displayPhones[0]}</a></li><li><a href={whatsappHref()} target="_blank" rel="noreferrer" className="flex items-center gap-3"><MessageCircle className="size-4.5 text-emerald-300"/>{siteConfig.whatsappDisplay} · WhatsApp</a></li><li><a href={`mailto:${siteConfig.email}`} className="flex items-center gap-3 break-all"><Mail className="size-4.5 shrink-0 text-emerald-300"/>{siteConfig.email}</a></li></ul></div>
  </div><div className="mt-12 grid gap-4 border-t border-white/10 pt-7 text-xs leading-5 text-slate-400 md:grid-cols-[1fr_auto]"><div><p>© {new Date().getFullYear()} {siteConfig.name}.</p><p className="mt-2 max-w-3xl"><BiText en="Website information is educational and does not replace diagnosis or individual medical advice. Never change prescribed medication without speaking to your clinician." te="వెబ్‌సైట్ సమాచారం సాధారణ అవగాహన కోసం మాత్రమే. వ్యక్తిగత నిర్ధారణ లేదా వైద్య సలహాను భర్తీ చేయదు. వైద్యుడితో మాట్లాడకుండా మందులను మార్చవద్దు."/></p></div><a href="/resources" data-i18n-link className="hover:text-white"><BiText en="Mental health resources" te="మానసిక ఆరోగ్య వనరులు"/></a></div></div></footer>;
}
