/* eslint-disable @next/next/no-img-element */
import { BiText } from "@/components/i18n/bilingual-text";
import { gallerySlides } from "@/data/gallery";

export function InlineGalleryPreview() {
  const first = gallerySlides[0];
  const data = gallerySlides.map(({ src, title, titleTe, alt, altTe, photoUrl, albumUrl }) => ({ src, title, titleTe, alt, altTe, url: photoUrl || albumUrl }));
  const script = `(function(){var root=document.getElementById('home-gallery');if(!root)return;var slides=${JSON.stringify(data).replace(/</g,"\\u003c")},i=0,playing=true,timer=null,img=root.querySelector('[data-image]'),title=root.querySelector('[data-title]'),count=root.querySelector('[data-count]'),source=root.querySelector('[data-source]'),toggle=root.querySelector('[data-toggle]'),startX=null,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;function isTe(){return document.documentElement.dataset.locale==='te'}function show(n){i=(n+slides.length)%slides.length;var s=slides[i];img.classList.remove('gallery-preview-image');void img.offsetWidth;img.src=s.src;img.alt=isTe()?s.altTe:s.alt;img.classList.add('gallery-preview-image');title.textContent=isTe()?s.titleTe:s.title;count.textContent=String(i+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');source.href=s.url}function stop(){if(timer)clearInterval(timer);timer=null}function start(){stop();if(playing&&!reduce)timer=setInterval(function(){show(i+1)},9000)}root.querySelector('[data-prev]').onclick=function(){show(i-1);start()};root.querySelector('[data-next]').onclick=function(){show(i+1);start()};toggle.onclick=function(){playing=!playing;toggle.textContent=playing?'Ⅱ':'▶';toggle.setAttribute('aria-label',playing?'Pause slideshow':'Play slideshow');start()};root.addEventListener('touchstart',function(e){startX=e.touches[0].clientX},{passive:true});root.addEventListener('touchend',function(e){if(startX===null)return;var d=e.changedTouches[0].clientX-startX;if(Math.abs(d)>45)show(i+(d>0?-1:1));startX=null;start()},{passive:true});root.addEventListener('keydown',function(e){if(e.key==='ArrowLeft')show(i-1);if(e.key==='ArrowRight')show(i+1)});root.addEventListener('mouseenter',stop);root.addEventListener('mouseleave',start);root.addEventListener('focusin',stop);root.addEventListener('focusout',function(e){if(!root.contains(e.relatedTarget))start()});var observer=new IntersectionObserver(function(entries){if(entries.some(function(e){return e.isIntersecting})){show(0);start();observer.disconnect()}},{rootMargin:'350px'});observer.observe(root)})();`;
  return <div id="home-gallery" className="bg-transparent" role="region" aria-roledescription="carousel" aria-label="Clinic archive gallery" tabIndex={0}><div className="relative aspect-[4/5] min-h-[26rem] overflow-hidden bg-transparent sm:aspect-[16/10] sm:min-h-[32rem]"><img data-image src={first.src} alt={first.alt} width={first.width} height={first.height} loading="lazy" decoding="async" className="gallery-preview-image absolute inset-0 h-full w-full object-contain"/><div className="absolute inset-x-0 bottom-0 h-36 bg-gradient-to-t from-slate-950/90 via-slate-950/45 to-transparent" aria-hidden="true"/><div className="absolute bottom-4 left-4 right-4 flex items-end justify-between gap-4 text-white md:bottom-6 md:left-7 md:right-7"><div><p data-count className="text-xs font-bold text-emerald-300">01 / {String(gallerySlides.length).padStart(2,"0")}</p><h3 data-title className="mt-1 text-lg font-extrabold md:text-2xl"><BiText en={first.title} te={first.titleTe}/></h3></div><a data-source href={first.photoUrl || first.albumUrl} target="_blank" rel="noreferrer" className="flex size-11 items-center justify-center rounded-full bg-white/15 text-white" aria-label="View original Facebook source">↗</a></div></div><div className="flex items-center gap-2 px-2 pt-4"><button data-prev type="button" className="size-11 rounded-full bg-muted/70 text-lg font-bold" aria-label="Previous gallery image">‹</button><button data-toggle type="button" className="size-11 rounded-full bg-muted/70 text-sm font-bold" aria-label="Pause slideshow">Ⅱ</button><button data-next type="button" className="size-11 rounded-full bg-muted/70 text-lg font-bold" aria-label="Next gallery image">›</button><span className="ml-2 text-xs text-muted-foreground"><BiText en="Slow autoplay · swipe on mobile" te="నెమ్మదైన ఆటోప్లే · మొబైల్‌లో స్వైప్"/></span></div><script dangerouslySetInnerHTML={{__html:script}}/></div>;
}
