import { CalendarDays, Phone, Sparkles, X } from "lucide-react";
import { BiText } from "@/components/i18n/bilingual-text";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/lib/site";

export function ExitIntent() {
  const script = `(function(){var d=document.getElementById('care-reminder');if(!d||matchMedia('(max-width: 900px)').matches)return;var seen=false;try{seen=!!sessionStorage.getItem('care-reminder-seen')}catch(e){}if(seen)return;var eligible=false,t=setTimeout(function(){eligible=true},25000);function leave(e){if(eligible&&e.clientY<=4&&!d.open){try{sessionStorage.setItem('care-reminder-seen','1')}catch(x){}d.showModal();document.removeEventListener('mouseout',leave);clearTimeout(t)}}document.addEventListener('mouseout',leave)})();`;
  return <><dialog id="care-reminder" className="fixed left-1/2 top-1/2 m-0 w-[min(92vw,34rem)] -translate-x-1/2 -translate-y-1/2 rounded-[2rem] border border-border bg-card p-7 text-foreground shadow-2xl backdrop:bg-slate-950/45 md:p-9"><form method="dialog"><button className="absolute right-4 top-4 flex size-10 items-center justify-center rounded-full hover:bg-muted" aria-label="Close"><X className="size-5"/></button></form><div className="flex size-12 items-center justify-center rounded-2xl bg-secondary/12 text-secondary"><Sparkles className="size-5"/></div><h2 className="mt-5 text-2xl font-extrabold"><BiText en="You can take the next step without having every answer." te="ప్రతి సమాధానం తెలియకపోయినా మొదటి అడుగు వేయవచ్చు."/></h2><p className="mt-3 text-sm leading-7 text-muted-foreground"><BiText en="A first consultation is a conversation—not a commitment to medication. Request a preferred time, and the clinic will confirm availability." te="మొదటి కన్సల్టేషన్ ఒక సంభాషణ—మందులకు ఒప్పందం కాదు. కోరిన సమయాన్ని పంపండి; క్లినిక్ అందుబాటును నిర్ధారిస్తుంది."/></p><div className="mt-6 flex flex-wrap gap-3"><Button asChild><a href="/appointment" data-i18n-link><CalendarDays/><BiText en="Request appointment" te="అపాయింట్‌మెంట్ కోరండి"/></a></Button><Button asChild variant="outline"><a href={`tel:${siteConfig.phones[0]}`}><Phone/><BiText en="Call clinic" te="క్లినిక్‌కు కాల్"/></a></Button></div><p className="mt-5 text-xs text-muted-foreground"><BiText en="Not for emergencies. For immediate danger in India, call 112." te="ఎమర్జెన్సీ కోసం కాదు. తక్షణ ప్రమాదంలో 112కు కాల్ చేయండి."/></p></dialog><script dangerouslySetInnerHTML={{__html:script}}/></>;
}
