import { CalendarDays, Phone } from "lucide-react";
import { FaWhatsapp } from "react-icons/fa";
import { BiText } from "@/components/i18n/bilingual-text";
import { siteConfig, whatsappHref } from "@/lib/site";

const bilingualMessage = "Hello Krishna Neuro Psychiatric Centre. I would like to request an appointment. / నమస్కారం. నాకు డా. పామర్తి కృష్ణ దాస్‌తో అపాయింట్‌మెంట్ కావాలి.";

export function FloatingActions() {
  return <><aside aria-label="Quick contact" className="fixed bottom-6 right-5 z-30 hidden flex-col gap-2 md:flex"><a href={whatsappHref(bilingualMessage)} target="_blank" rel="noreferrer" className="group flex h-12 items-center justify-end gap-2 rounded-full bg-[#178e52] px-3.5 text-sm font-bold text-white shadow-xl transition-all hover:-translate-y-1"><span className="max-w-0 overflow-hidden whitespace-nowrap opacity-0 transition-all group-hover:max-w-40 group-hover:opacity-100">{siteConfig.whatsappDisplay}</span><FaWhatsapp className="size-5"/></a><a href={`tel:${siteConfig.phones[0]}`} className="group flex h-12 items-center justify-end gap-2 rounded-full bg-primary px-3.5 text-sm font-bold text-primary-foreground shadow-xl transition-all hover:-translate-y-1"><span className="max-w-0 overflow-hidden whitespace-nowrap opacity-0 transition-all group-hover:max-w-28 group-hover:opacity-100"><BiText en="Call now" te="కాల్ చేయండి"/></span><Phone className="size-5"/></a></aside><aside aria-label="Appointment actions" className="mobile-appointment-actions safe-bottom fixed inset-x-0 bottom-0 z-40 border-t border-border bg-card/94 px-3 pt-2 shadow-[0_-12px_32px_-20px_rgb(15_23_42/.45)] backdrop-blur-xl md:hidden"><div className="mx-auto grid max-w-md grid-cols-[.8fr_.8fr_1.25fr] gap-2"><a href={`tel:${siteConfig.phones[0]}`} className="flex min-h-11 flex-col items-center justify-center gap-0.5 rounded-xl bg-muted text-[0.66rem] font-bold text-foreground"><Phone className="size-4.5 text-primary"/><BiText en="Call" te="కాల్"/></a><a href={whatsappHref(bilingualMessage)} target="_blank" rel="noreferrer" className="flex min-h-11 flex-col items-center justify-center gap-0.5 rounded-xl bg-emerald-50 text-[0.66rem] font-bold text-emerald-800 dark:bg-emerald-950/35 dark:text-emerald-300"><FaWhatsapp className="size-4.5"/>WhatsApp</a><a href="/appointment" data-i18n-link className="flex min-h-11 items-center justify-center gap-1.5 rounded-xl bg-primary px-3 text-xs font-extrabold text-primary-foreground"><CalendarDays className="size-4.5"/><BiText en="Book appointment" te="అపాయింట్‌మెంట్"/></a></div></aside></>;
}
