import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, FileText, LockKeyhole, MessageCircleQuestion, NotebookPen, Pill, UserRoundCheck } from "lucide-react";
import { Reveal } from "@/components/motion/reveal";
import { AppointmentCTA } from "@/components/shared/appointment-cta";
import { PageHero } from "@/components/shared/page-hero";
import { PatientJourney, journeySteps } from "@/components/shared/patient-journey";
import { SectionHeading } from "@/components/shared/section-heading";
import { Button } from "@/components/ui/button";
import { createMetadata } from "@/lib/metadata";

export const metadata: Metadata = createMetadata({ title: "Your Psychiatry Appointment Journey", description: "Know what to expect from booking, first consultation, assessment, diagnosis, personalised treatment, follow-up and long-term wellbeing.", path: "/patient-journey" });

export default function PatientJourneyPage() {
  return (
    <>
      <PageHero badge="What to expect" title="A clear journey makes the first step feel lighter." description="You deserve to know how appointments work, what information helps and how decisions are made. No mystery, no automatic medication, no pressure to share everything at once." breadcrumbs={[{label:"Patient journey"}]} actions={<Button asChild><Link prefetch={false} href="/appointment">Begin with a request<ArrowRight/></Link></Button>} />
      <section className="container-page py-16 md:py-22"><PatientJourney compact /></section>
      <section className="border-y border-border bg-muted/55 py-16 md:py-22"><div className="container-page"><Reveal><SectionHeading eyebrow="Step by step" title="What each stage is designed to do" /></Reveal><ol className="mt-10 grid gap-5">{journeySteps.map((step,index)=>{const Icon=step.icon;return <li key={step.title} className="grid gap-5 rounded-[1.6rem] border border-border bg-card p-6 shadow-card md:grid-cols-[auto_1fr_.7fr] md:items-center"><span className="flex size-12 items-center justify-center rounded-2xl bg-primary/8 text-primary"><Icon className="size-5"/></span><div><p className="text-[0.66rem] font-extrabold uppercase tracking-[0.12em] text-muted-foreground">Step {index+1}</p><h2 className="mt-1.5 text-xl font-extrabold tracking-[-0.03em]">{step.title}</h2></div><p className="text-sm leading-6 text-muted-foreground">{step.text}</p></li>})}</ol></div></section>
      <section className="container-page py-16 md:py-22"><div className="grid gap-12 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="Prepare without pressure" title="Helpful things to bring"/><ul className="mt-7 grid gap-4">{[{i:Pill,t:"Current medicines",d:"Names, doses, supplements and photos of strips are useful."},{i:NotebookPen,t:"A simple timeline",d:"When the change began, major events and what has helped or worsened it."},{i:FileText,t:"Relevant reports",d:"Discharge notes, laboratory tests or past prescriptions—if readily available."},{i:MessageCircleQuestion,t:"Your questions",d:"Write down what you most want to understand before leaving."}].map(x=>{const Icon=x.i;return <li key={x.t} className="flex gap-4 rounded-2xl border border-border bg-card p-5"><Icon className="mt-0.5 size-5 shrink-0 text-secondary"/><div><h3 className="font-extrabold">{x.t}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{x.d}</p></div></li>})}</ul><p className="mt-5 text-xs leading-6 text-muted-foreground">Do not delay urgent care to collect documents. Honest information is more useful than perfect paperwork.</p></Reveal><Reveal delay={0.08}><SectionHeading eyebrow="Your rights in care" title="Respect is part of treatment."/><ul className="mt-7 grid gap-4">{["Ask what a diagnosis means and what remains uncertain.","Understand the purpose, benefits and risks of a proposed treatment.","Ask about alternatives and what may happen without treatment.","Request privacy and understand its safety and legal limits.","Bring a trusted person or ask for part of the visit alone.","Seek a second opinion without criticism of another clinician."].map(x=><li key={x} className="flex gap-3 text-sm leading-6 text-muted-foreground"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-secondary/12 text-secondary"><Check className="size-3" strokeWidth={3}/></span>{x}</li>)}</ul><div className="mt-8 flex gap-4 rounded-2xl border border-primary/15 bg-primary/6 p-5"><LockKeyhole className="size-5 shrink-0 text-primary"/><p className="text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Privacy:</strong> personal information is handled confidentially within professional, safety and legal limits. Ask if you are unsure who can receive information.</p></div></Reveal></div></section>
      <section className="border-y border-border bg-card py-14"><div className="container-page flex flex-col items-center justify-between gap-6 rounded-[1.8rem] bg-muted/60 p-7 text-center md:flex-row md:text-left"><div className="flex items-center gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-secondary/10 text-secondary"><UserRoundCheck/></span><div><h2 className="text-xl font-extrabold">A requested time is not yet confirmed.</h2><p className="mt-1 text-sm text-muted-foreground">The clinic will reply with availability and practical details.</p></div></div><Button asChild><Link prefetch={false} href="/appointment">Request a time<ArrowRight/></Link></Button></div></section>
      <AppointmentCTA />
    </>
  );
}
